services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODEL_NAME: gpt2
      INFERENCE_BACKEND: hf
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
